### ISSUE TITLE
Failed to activate the recent-projects package

### ISSUE THREAD

**Issue by vnt** [EXSyst/recent-projects#51] opened 2017-03-20 08:28 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package 0.13.1

### Stack Trace

Failed to activate the recent-projects package

```
At 'super' keyword unexpected here

SyntaxError: 'super' keyword unexpected here
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/recent-projects/lib/main.js:8:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
     -0:16.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.3.0 
cakephp3-snippets 0.5.0 
chrome-color-picker 0.8.0 
color-picker 2.2.5 
color-tabs 0.1.8 
css-color-name 0.4.0 
file-icons 2.0.17 
file-types 0.5.5 
git-plus 7.3.3 
git-time-machine 1.5.6 
goto-definition 1.2.1 
intentions 1.1.2 
language-smarty 1.8.0 
linter 2.1.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-php 1.3.2 
linter-ui-default 1.2.1 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
open-recent 5.0.0 
pigments 0.39.1 
pinegrow-atom 0.3.1 
recent-projects 0.13.1 
simple-drag-drop-text 0.3.4 
tag 0.4.0 
todo-show 1.11.0 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
tree-view-autoresize 1.6.0 
```

**Comment by GuilhemN** [comment] 2017-03-20 08:29
Duplicate of https://github.com/EXSyst/recent-projects/issues/50.

**Closed as completed by GuilhemN** 2017-03-20 08:29 UTC
