### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by wsargent** [EXSyst/recent-projects#19] opened 2015-02-03 19:15 UTC
[Enter steps to reproduce below:]

1. Open project.
2. EXPLODE.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.1
**Thrown From**: [recent-projects](https://github.com/Exter-N/recent-projects) package, v0.3.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/wsargent/.atom/packages/recent-projects/lib/recent-projects.coffee:59

TypeError: undefined is not a function
  at fn (/Users/wsargent/.atom/packages/recent-projects/lib/recent-projects.coffee:59:24)
  at /Users/wsargent/.atom/packages/recent-projects/lib/recent-projects.coffee:42:13
  at /Users/wsargent/.atom/packages/recent-projects/lib/recent-projects.coffee:26:25
  at FSReqWrap.cb [as oncomplete] (fs.js:229:19)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "markdown-stream",
      "metrics"
    ],
    "themes": [
      "atom-light-ui",
      "fizzy"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.4.2
atomatigit, v1.2.3
dash, v1.0.2
emmet, v2.3.3
file-icon-supplement, v0.7.2
fizzy, v0.15.0
git-diff-details, v0.5.0
git-log, v0.2.0
git-tab-status, v1.5.3
language-asciidoc, v0.11.1
language-docker, v1.1.2
language-gfm, v0.63.0
language-gitignore, v0.1.1
language-scala, v1.1.0
minimap, v4.0.2
minimap-git-diff, v3.1.1
recent-files, v0.3.0
recent-projects, v0.3.0
saveallthetime, v0.1.1
soft-wrap-indicator, v0.4.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by ponychicken** [comment] 2015-02-04 10:26
Might be caused by Atom update (just updated and got this as well)

**Comment by BlaM** [comment] 2015-02-04 13:09
Same Error here - just want to add that I didn't open an project, but only went for "Open Folder..." (in a folder that was never opened before) and still got the error. No obvious involvement of project manager at all.

**Comment by vraravam** [comment] 2015-02-12 02:14
I just uninstalled recent-projects, and reinstalled it, and boom - the same issue.

**Comment by witeshadow** [comment] 2015-02-13 18:01
Got this on Win 8.1

**Comment by Moter8** [comment] 2015-02-14 21:47
Same here - Win10 Atom `0.177.0`

**Comment by masqita** [comment] 2015-02-16 10:26
The issue seems to be with the findIndex function call (an ES6 array function). The function doesn't seem to be available in atom anymore since the last update. I tried literally inserting `use "6to5";` into the coffeescript file, but that doesn't seem to work. Polyfilling the findIndex function does work, but it just doesn't feel right.

**Comment by ponychicken** [comment] 2015-02-16 10:35
@masqita Thanks for pinpointing this. Atom switched to iojs as the node version, and indeed in the current io.js findIndex is undefined. This should not be the case, I'll be filing a bug upstream. The best thing for now imo would be to rewrite the offending function and loop over the array manually.

**Comment by ponychicken** [comment] 2015-02-16 10:41
Interestlingly enough it's actually due to a change in v8. It might have been enabled by default before but right now it's behind the  --harmony_arrays flag.

**Comment by Moter8** [comment] 2015-04-20 15:52
**Still** exists.

**Comment by Ener-Getick** [comment] 2015-07-01 10:07
Fixed by https://github.com/EXSyst/recent-projects/commit/b68d92dbf54ba8867f3d20292558b1596324981d.
Thank you.

**Closed by Ener-Getick** 2015-07-01 10:07 UTC
