### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

### ISSUE THREAD

**Issue by lorenzoferrone** [EXSyst/recent-projects#49] opened 2016-11-14 15:25 UTC
The error in the title appear when I try to click on the "Open Folder..." button in the main screen of the package.

Follows the auto-generated in formation from the Atom:

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

```
At /Users/lorenzo/.atom/packages/recent-projects/lib/recent-projects-view.js:483

TypeError: Cannot read property 'showOpenDialog' of undefined
    at RecentProjectsView.openFolder (/Users/lorenzo/.atom/packages/recent-projects/lib/recent-projects-view.js:483:9)
    at HTMLButtonElement.<anonymous> (/Users/lorenzo/.atom/packages/recent-projects/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Users/lorenzo/.atom/packages/recent-projects/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/lorenzo/.atom/packages/recent-projects/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:04.6.0 recent-projects:open (atom-text-editor.editor.is-focused)
     -1:39.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:46 recent-projects:open (atom-text-editor.editor.mini.is-focused)
```

**Comment by JoniWeiss** [comment] 2016-11-18 00:56
I'm getting the same error:
Atom Version: 1.12.4
System: macOS 10.12.2 Beta (16C41b)

Thrown From: recent-projects package, v0.13.0 Atom 

Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

# Stack Trace:
```
TypeError: Cannot read property 'showOpenDialog' of undefined
    at RecentProjectsView.openFolder (/Users/joniweiss/.atom/packages/recent-projects/lib/recent-projects-view.js:483:9)
    at HTMLButtonElement.<anonymous> (/Users/joniweiss/.atom/packages/recent-projects/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Users/joniweiss/.atom/packages/recent-projects/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/joniweiss/.atom/packages/recent-projects/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by ronilaukkarinen** [comment] 2016-11-18 12:55
Also here.

Atom: 1.12.3
System: Mac OS X 10.11.6

`/Users/rolle/.atom/packages/recent-projects/lib/recent-projects-view.js:483`

# Stack Trace

````
TypeError: Cannot read property 'showOpenDialog' of undefined
    at RecentProjectsView.openFolder (/Users/rolle/.atom/packages/recent-projects/lib/recent-projects-view.js:483:9)
    at HTMLButtonElement.<anonymous> (/Users/rolle/.atom/packages/recent-projects/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Users/rolle/.atom/packages/recent-projects/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/rolle/.atom/packages/recent-projects/node_modules/jquery/dist/jquery.js:4121:28)
````

**Comment by GuilhemN** [comment] 2016-11-18 16:29
Thanks for the report! That's probably caused by an atom update, I'll take a look at it :)

**Comment by GuilhemN** [comment] 2016-11-18 17:56
Fixed in https://github.com/EXSyst/recent-projects/commit/90fa44d73e7786ac6ff9ba49d205f0d802f4bc48, thanks again!

**Closed** 2016-11-18 17:55 UTC
